embed_dim: 256

hidden_dim: 512

learning_rate: 0.0001

batch_size: 4

epochs: 2

max_text_length: 64

vocab_size: 30522

image_size: 224

model_name: distilbert-base-uncased

dataset_name: daniel3303/StoryReasoning

optimizer: AdamW

loss_functions:
  - CrossEntropyLoss
  - ContrastiveLoss

evaluation_metrics:
  - BLEU
  - ROUGE-L
  - METEOR

innovation:
  - Contrastive Multimodal Alignment
  - Temporal LSTM Reasoning
  - GradCAM Explainability